# -*- coding: utf-8 -*-
"""Lecture 2 Conditional execution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1daVH_j0dxc4A6pSdmHMSNuYpDaRzlL3N

# Contents
## 1. Boolean Expression
## 2. Comparison Operators
## 3. Logical Operators
## 4. if Statement
## 5. Catching exceptions using try and except
## 6. Short circuit evaluation of logical expressions

# 1. Boolean Expressions

A boolean expression is an expression that is either true or false.
"""

5==5

5==8

type(True)

# what is type of False

"""# 2. Comparison Operators

x == y # x is equal to y

x != y # x is not equal to y

x > y # x is greater than y

x < y # x is less than y

x >= y # x is greater than or equal to y

x <= y # x is less than or equal to y

x is y # x is the same as y

x is not y # x is not the same as y
"""

# if x = 10 and y = 10, which of the above statements will return True

# if x = 10 and y = 30, which of the above statements will return False

# write the comparsion operators which are common in above two

"""# 3. Logical operators

There are three logical operators: and, or, and not
"""

x = 6
print (x > 0 and x < 10)

print (not (x%2 == 0))

17 and True

# what will be the output of 0 or True

# what will be the output of 1 and False

"""# 4. if Statement"""

x = 5
if x > 0 :
    print ("x is positive")
    print ("value of x is = ", x)

# you can use the pass statement, which does nothing
x = 6
if x < 0 :
    pass

"""### Alternative execution"""

x = 5
if x%2 == 0 :
    print ('x is even')
else :
    print ('x is odd')

"""### Chained conditionals"""

x = 12
y = 2
if x < y:
    print ('x is less than y')
elif x > y:
    print ('x is greater than y')
else:
    print ('x and y are equal')

choice = 'b'
if choice == 'a':
    print ('Bad guess')
elif choice == 'b':
    print ('Good guess')
elif choice == 'c':
    print ('Close, but not correct')

# Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range 
# print an error. If the score is between 0.0 and 1.0, print a grade using the following 
# table:
# Score Grade
# >= 0.9 A
# >= 0.8 B
# >= 0.7 C
# >= 0.6 D
# < 0.6 F

"""### Nested conditions"""

x = 5
y = 23
if x == y:
    print ('x and y are equal')
else:
    if x < y:
        print ('x is less than y')
    else:
        print ('x is greater than y')

"""# 5. Catching exceptions using try and except

The idea of try and except is that you know that some sequence of instruction(s) may have a problem and
you want to add some statements to be executed if an error occurs. 

These extra statements (the except block) are ignored if there is no error.

You can think of the try and except feature in Python as an “insurance policy”
on a sequence of statements.
"""

inp = input('Enter Fahrenheit Temperature:')
fahr = float(inp)
cel = (fahr - 32.0) * 5.0 / 9.0
print (cel)

inp = input('Enter Fahrenheit Temperature:')
try:
    fahr = float(inp)
    cel = (fahr - 32.0) * 5.0 / 9.0
    print (cel)
except:
    print ('Please enter a number')

"""Handling an exception with a try statement is called catching an exception. 
In this example, the except clause prints an error message. 
In general, catching an exception gives you a chance to fix the problem, or try again, or at least end the program gracefully.

Rewrite your pay program using try and except so that your program handles non-numeric input gracefully by printing a message and exiting the program. The following shows two executions of the program:
    
Enter Hours: 20
Enter Rate: nine
Error, please enter numeric input
Enter Hours: forty
Error, please enter numeric input

# 6. Short circuit evaluation of logical expressions

When Python is processing a logical expression such as x >= 2 and (x/y) > 2, it evaluates the expression from left-to-right. 

Because of the definition of and, if x is less than 2, the expression x >= 2 is False and so the whole expression is False regardless of whether (x/y) > 2 evaluates to True or False.

When Python detects that there is nothing to be gained by evaluating the rest of a logical expression, it stops its evaluation and does not do the computations in the rest of the logical expression. 

When the evaluation of a logical expression stops because the overall value is already known, it is called short-circuiting the evaluation.
"""

x = 6
y = 2
x >= 2 and (x/y) > 2

x = 1
y = 0
x >= 2 and (x/y) > 2

# what will happen here???
x = 6
y = 0
x >= 2 and (x/y) > 2

"""The third calculation failed because Python was evaluating (x/y) and y was zero which causes a runtime error. 

But the second example did not fail because the first part of the expression x >= 2 evaluated to False so the (x/y) was not ever executed due to the short circuit rule and there was no error.

We can construct the logical expression to strategically place a guard evaluation just before the evaluation that might cause an error as follows:
"""

x = 1
y = 0
x >= 2 and y != 0 and (x/y) > 2

x = 6
y = 0
x >= 2 and y != 0 and (x/y) > 2

# what will happen if you execute x >= 2 and (x/y) > 2 and y != 0

"""In the second expression, we say that y != 0 acts as a guard to insure that we only execute (x/y) if y is non-zero."""